colors:
  cursor:
    cursor: '#eeeeee'

  # Default Colours
  primary:
    background: '#0d0d0d'
    foreground: '#eeeeee'

  # Normal Colours
  normal:
    black: '#1f1f1f'
    red: '#f92645'
    green: '#82b414'
    yellow: '#fdbe25'
    blue: '#0c68af'
    magenta: '#8c54fe'
    cyan: '#13a5a2'
    white: '#858585'

  # Bright Colours
  bright:
    black: '#454545'
    red: '#ff7184'
    green: '#bce368'
    yellow: '#feee78'
    blue: '#67a9dc'
    magenta: '#b28cfe'
    cyan: '#8fe3de'
    white: '#ffffff'

env:
  TERM: 'xterm-256color'

font:
  size: 11
  normal:
    family: 'monospace'

window:
  dynamic_padding: true
