# Set umask to 027 (default directory mode 750, file mode 640)
umask 027

# Load user binary directories into path
if [ -d "${HOME}/bin" ]
then
	PATH="${HOME}/bin:${PATH}"
fi

if [ -d "${HOME}/.local/bin" ]
then
	PATH="${HOME}/.local/bin:${PATH}"
fi

# Set GPG TTY
GPG_TTY=$(tty)
