# TODO: Need to check the correct way to handle .profile and .bashrc in the different ways a shell can be launched

# If not running bash, do nothing
if [ -z "${BASH_VERSION}" ]
then
	return
fi

BASHRC="${HOME}/.bashrc"

if [ -f "${BASHRC}" ] && [ -r "${BASHRC}" ]
then
	# shellcheck source=/dev/null
	. "${BASHRC}"
fi
