case "${TERM}" in
	xterm-color|\
	*-256color)
		# Colour prompt is supported by terminal
		COLOR_PROMPT=1
		;;
esac

if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null
then
	# tput is available
	COLOR_PROMPT=2
fi

if [ "${COLOR_PROMPT}" = 2 ]
then
	COLOR_RESET="\e[00m"

	COLOR_USER_HOST="\e[01;32m"
	COLOR_PWD="\e[01;34m"
fi

SUFFIX="$ "

if [ "${UID}" = 0 ]
then
	SUFFIX="# "

	if [ "${COLOR_PROMPT}" = 2 ]
	then
	
		COLOR_USER_HOST="\e[31m"
	fi
fi

PS1="${COLOR_USER_HOST:-}\u@\h${COLOR_RESET:-}:${COLOR_PWD:-}\w${COLOR_RESET:-}${SUFFIX:-}"
